### ISSUE TITLE
Request: More settings

### ISSUE THREAD

**Issue by Kikithecat12345** [samfundev/KtaneTwitchPlays#496]
Ideas for settings: 
 Number of Note Slots on screen
 Colour options (for stuff like module #s and Usernames)
 whatever else may be interesting or helpful to be able to change

**Comment by Kikithecat12345** [comment]
damn it formatting

**Comment by samfun123** [comment]
1. I'd much rather change the number of note slots to be something that everyone is happy with then adding a setting for it. Unless there is a real need for having something be configurable, I'm not going to add a setting.
2. Although it's not documented, you can already set the color of the module IDs. I don't know what you mean by username colors, those are based on what someone's color is in chat.
3. You'll need to be more specific, otherwise I can never close this issue.

**Comment by Kikithecat12345** [comment]
You basically answered the request verbatim. other than those 2 (and your reason is good to not add them) I feel a good setting would be to be able to turn off the leaderboard/points system.

**Comment by samfun123** [comment]
Like I said, if you can find streamers who would want to have that I'd be willing to add it but there's no point in me adding something that people aren't going to use. Especially because there is already a ton of settings already and I feel like we could probably remove some of them.

**Comment by samfundev** [comment]
Closing due to lack of information.
